In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
lines = [
    "The quick brown fox",
    "jumps over the lazy dog",
    "and runs into the forest",
    "where it finds a hidden path",
    "leading to an ancient castle"
]


In [3]:
lines

['The quick brown fox',
 'jumps over the lazy dog',
 'and runs into the forest',
 'where it finds a hidden path',
 'leading to an ancient castle']

In [4]:
##define vocabulary size
voc_size = 10000

In [5]:
#one hot representation for everyword
one_hot_repr = [one_hot(words,voc_size)for words in lines]
one_hot_repr

[[305, 2733, 72, 3513],
 [2539, 4456, 305, 3418, 577],
 [3519, 6277, 9172, 305, 8368],
 [3365, 3234, 4755, 2229, 9090, 8023],
 [2011, 4016, 1350, 2184, 2184]]

In [6]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs=pad_sequences(one_hot_repr,padding = 'pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  305 2733   72 3513]
 [   0    0    0 2539 4456  305 3418  577]
 [   0    0    0 3519 6277 9172  305 8368]
 [   0    0 3365 3234 4755 2229 9090 8023]
 [   0    0    0 2011 4016 1350 2184 2184]]


In [9]:
#feature represntation
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','')

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)